"""Socle initial — 8 tables + 2 triggers (schéma validé le 2026-07-28).

Tables générées par autogénération depuis app/models.py (zéro dérive).
Les triggers, non exprimables en contraintes déclaratives, sont ajoutés à la
main en fin d'upgrade :
- images_gel_crop (SQLSTATE CW001) : la géométrie de crop devient immuable dès
  qu'une image porte au moins une annotation — un recadrage crée une nouvelle
  ligne images, il ne modifie jamais l'existante ;
- images_transition_statut (SQLSTATE CW002) : liste blanche des transitions de
  statut, identique à models.IMAGE_STATUS_TRANSITIONS (toute évolution doit
  toucher les deux).

Revision ID: 0001
Revises:
Create Date: 2026-07-28 11:56:23.341696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('annotateur', 'annotateur_confirme', 'administrateur')", name=op.f('ck_users_role_valide')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_sessions'))
    )
    op.create_index('ix_auth_sessions_last_seen', 'auth_sessions', ['last_seen_at'], unique=False)
    op.create_index('ix_auth_sessions_user', 'auth_sessions', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('lighting', sa.Text(), nullable=True),
    sa.Column('camera_height_cm', sa.Integer(), nullable=True),
    sa.Column('compost_state', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sessions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('name', name=op.f('uq_sessions_name'))
    )
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_batches_created_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_batches_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('id', 'session_id', name='uq_batches_id_session'),
    sa.UniqueConstraint('session_id', 'name', name='uq_batches_session_name')
    )
    op.create_table('batch_assignments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.BigInteger(), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("release_reason IS NULL OR release_reason IN ('termine', 'rendu', 'force_admin')", name=op.f('ck_batch_assignments_motif_liberation_valide')),
    sa.CheckConstraint('(released_at IS NULL) = (release_reason IS NULL)', name=op.f('ck_batch_assignments_motif_liberation_coherent')),
    sa.CheckConstraint('(released_at IS NULL) = (released_by IS NULL)', name=op.f('ck_batch_assignments_liberation_coherente')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_batch_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_assignments_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_batch_assignments_released_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_batch_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_assignments'))
    )
    op.create_index('ix_batch_assignments_user', 'batch_assignments', ['user_id'], unique=False)
    op.create_index('uq_batch_assignments_actif', 'batch_assignments', ['batch_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('images',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('export_filename', sa.Text(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('cropped_path', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('crop_x', sa.Integer(), nullable=True),
    sa.Column('crop_y', sa.Integer(), nullable=True),
    sa.Column('cropped_width', sa.Integer(), nullable=True),
    sa.Column('cropped_height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'en_attente_preannotation'"), nullable=False),
    sa.Column('annotated_by', sa.BigInteger(), nullable=True),
    sa.Column('annotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('superseded_by_id IS NULL OR superseded_at IS NOT NULL', name=op.f('ck_images_archivage_coherent')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_images_sha256_hex')),
    sa.CheckConstraint("status <> 'relue' OR reviewed_by IS NOT NULL", name=op.f('ck_images_relue_a_un_relecteur')),
    sa.CheckConstraint("status IN ('en_attente_preannotation', 'a_annoter', 'en_cours', 'annotee', 'relue')", name=op.f('ck_images_statut_valide')),
    sa.CheckConstraint('(annotated_by IS NULL) = (annotated_at IS NULL)', name=op.f('ck_images_annotation_horodatee')),
    sa.CheckConstraint('(cropped_path IS NULL AND crop_x IS NULL AND crop_y IS NULL AND cropped_width IS NULL AND cropped_height IS NULL) OR (cropped_path IS NOT NULL AND crop_x IS NOT NULL AND crop_y IS NOT NULL AND cropped_width IS NOT NULL AND cropped_height IS NOT NULL)', name=op.f('ck_images_crop_complet_ou_absent')),
    sa.CheckConstraint('(reviewed_by IS NULL) = (reviewed_at IS NULL)', name=op.f('ck_images_relecture_horodatee')),
    sa.CheckConstraint('crop_x IS NULL OR (crop_x >= 0 AND crop_y >= 0 AND cropped_width > 0 AND cropped_height > 0)', name=op.f('ck_images_crop_geometrie_valide')),
    sa.CheckConstraint('reviewed_by IS NULL OR reviewed_by <> annotated_by', name=op.f('ck_images_relecteur_different_annotateur')),
    sa.CheckConstraint('width > 0 AND height > 0', name=op.f('ck_images_dimensions_positives')),
    sa.ForeignKeyConstraint(['annotated_by'], ['users.id'], name=op.f('fk_images_annotated_by_users')),
    sa.ForeignKeyConstraint(['batch_id', 'session_id'], ['batches.id', 'batches.session_id'], name='fk_images_batch_session'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_images_reviewed_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_images_session_id_sessions')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['images.id'], name=op.f('fk_images_superseded_by_id_images')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('cropped_path', name=op.f('uq_images_cropped_path'))
    )
    op.create_index('ix_images_batch_statut', 'images', ['batch_id', 'status'], unique=False, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_index('ix_images_file_preannotation', 'images', ['id'], unique=False, postgresql_where=sa.text("status = 'en_attente_preannotation' AND superseded_at IS NULL"))
    op.create_index('ix_images_session', 'images', ['session_id'], unique=False)
    op.create_index('ix_images_sha256', 'images', ['sha256'], unique=False)
    op.create_index('uq_images_original_path_actif', 'images', ['original_path'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_index('uq_images_sha256_actif', 'images', ['sha256'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_index('uq_images_session_export_actif', 'images', ['session_id', 'export_filename'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_table('annotations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.SmallInteger(), nullable=False),
    sa.Column('x_center', sa.Double(), nullable=False),
    sa.Column('y_center', sa.Double(), nullable=False),
    sa.Column('box_width', sa.Double(), nullable=False),
    sa.Column('box_height', sa.Double(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'proposee'"), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(source = 'humain') = (created_by IS NOT NULL)", name=op.f('ck_annotations_auteur_humain_coherent')),
    sa.CheckConstraint("(state = 'proposee') = (decided_by IS NULL)", name=op.f('ck_annotations_decision_a_un_auteur')),
    sa.CheckConstraint("source <> 'humain' OR confidence IS NULL", name=op.f('ck_annotations_confidence_modele_seul')),
    sa.CheckConstraint("source <> 'humain' OR model_name IS NULL", name=op.f('ck_annotations_model_name_modele_seul')),
    sa.CheckConstraint("source IN ('modele', 'humain')", name=op.f('ck_annotations_source_valide')),
    sa.CheckConstraint("state IN ('proposee', 'validee', 'rejetee')", name=op.f('ck_annotations_etat_valide')),
    sa.CheckConstraint('(decided_by IS NULL) = (decided_at IS NULL)', name=op.f('ck_annotations_decision_horodatee')),
    sa.CheckConstraint('(updated_by IS NULL) = (updated_at IS NULL)', name=op.f('ck_annotations_retouche_horodatee')),
    sa.CheckConstraint('class_id >= 0', name=op.f('ck_annotations_class_id_positif')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_annotations_confidence_normalisee')),
    sa.CheckConstraint('x_center BETWEEN 0 AND 1 AND y_center BETWEEN 0 AND 1 AND box_width > 0 AND box_width <= 1 AND box_height > 0 AND box_height <= 1', name=op.f('ck_annotations_coordonnees_normalisees')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_annotations_created_by_users')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_annotations_decided_by_users')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_annotations_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_annotations_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations'))
    )
    op.create_index('ix_annotations_image_state', 'annotations', ['image_id', 'state'], unique=False)
    op.create_table('image_status_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('en_attente_preannotation', 'a_annoter', 'en_cours', 'annotee', 'relue')", name=op.f('ck_image_status_events_statut_origine_valide')),
    sa.CheckConstraint("to_status IN ('en_attente_preannotation', 'a_annoter', 'en_cours', 'annotee', 'relue')", name=op.f('ck_image_status_events_statut_cible_valide')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_image_status_events_changed_by_users')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_image_status_events_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_status_events'))
    )
    op.create_index('ix_image_status_events_image', 'image_status_events', ['image_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###

    # ── Triggers (écrits à la main, voir docstring) ──────────────────────────
    op.execute("""
        CREATE FUNCTION trg_images_gel_crop() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF (NEW.cropped_path IS DISTINCT FROM OLD.cropped_path
                OR NEW.crop_x IS DISTINCT FROM OLD.crop_x
                OR NEW.crop_y IS DISTINCT FROM OLD.crop_y
                OR NEW.cropped_width IS DISTINCT FROM OLD.cropped_width
                OR NEW.cropped_height IS DISTINCT FROM OLD.cropped_height)
               AND EXISTS (SELECT 1 FROM annotations WHERE image_id = OLD.id) THEN
                RAISE EXCEPTION
                    'geometrie de crop immuable : l''image % porte des annotations (recadrage = nouvelle ligne images)',
                    OLD.id
                    USING ERRCODE = 'CW001';
            END IF;
            RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER images_gel_crop
        BEFORE UPDATE ON images
        FOR EACH ROW EXECUTE FUNCTION trg_images_gel_crop();
    """)
    op.execute("""
        CREATE FUNCTION trg_images_transition_statut() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.status IS DISTINCT FROM OLD.status
               AND (OLD.status, NEW.status) NOT IN (
                   ('en_attente_preannotation', 'a_annoter'),
                   ('a_annoter', 'en_cours'),
                   ('en_cours', 'a_annoter'),
                   ('en_cours', 'annotee'),
                   ('annotee', 'relue'),
                   ('annotee', 'en_cours'),
                   ('relue', 'en_cours')
               ) THEN
                RAISE EXCEPTION
                    'transition de statut interdite : % -> % (image %)',
                    OLD.status, NEW.status, OLD.id
                    USING ERRCODE = 'CW002';
            END IF;
            RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER images_transition_statut
        BEFORE UPDATE ON images
        FOR EACH ROW EXECUTE FUNCTION trg_images_transition_statut();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER images_transition_statut ON images")
    op.execute("DROP FUNCTION trg_images_transition_statut()")
    op.execute("DROP TRIGGER images_gel_crop ON images")
    op.execute("DROP FUNCTION trg_images_gel_crop()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_status_events_image', table_name='image_status_events')
    op.drop_table('image_status_events')
    op.drop_index('ix_annotations_image_state', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index('uq_images_session_export_actif', table_name='images', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_index('uq_images_sha256_actif', table_name='images', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_index('uq_images_original_path_actif', table_name='images', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_index('ix_images_sha256', table_name='images')
    op.drop_index('ix_images_session', table_name='images')
    op.drop_index('ix_images_file_preannotation', table_name='images', postgresql_where=sa.text("status = 'en_attente_preannotation' AND superseded_at IS NULL"))
    op.drop_index('ix_images_batch_statut', table_name='images', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_table('images')
    op.drop_index('uq_batch_assignments_actif', table_name='batch_assignments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('ix_batch_assignments_user', table_name='batch_assignments')
    op.drop_table('batch_assignments')
    op.drop_table('batches')
    op.drop_table('sessions')
    op.drop_index('ix_auth_sessions_user', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_last_seen', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
